name: Build and Deploy .NET App to Azure

on:
  push:
    branches:
      - none

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore Dependencies
      run: dotnet restore ./SimpleDotNetApp

    - name: Build Application
      run: dotnet build ./SimpleDotNetApp --configuration Release --no-restore

    - name: Publish Application
      run: dotnet publish ./SimpleDotNetApp --configuration Release --output ./publish --no-restore

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: simple-dotnet-app-02598
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
